== GUBG

_Generic Utilities by GUBG_

Welcome to the home of GUBG. This software package implements general functionality:

* Artificial intelligence: not so much is actually there yet, but it will come
* Compilation, documentation and test management: gb is a generic build tool that can compile and run tests, and in the future can create documentation
* Visualization
* Gaming and physics
* Configuration files for gvim, mucommander, emacs, bash etc.

== Languages
* $$C++$$: Current development is mainly for $$C++$$. Some of the earlier code was also written in $$C++$$, after some experimentation with D and D2, all effort is back on $$C++$$.
* http://www.digitalmars.com/d[D] is great, both branches for D1 and D2 exist. Currently, development for D is paused
* Ruby: Great for doing various things

== Platforms
* Linux/GNU: Arch linux, Ubuntu, LinuxMint and Kubuntu were tested
* Win32 is less supported, but some things should run

== Compilers
* gcc 4.6.3
* Microsoft cl 16

== Support
None at all, any questions, comments or suggestions are always welcome at geert_dot_fannes_at_gmail_dot_com
