opencv2:
	g++ opencv_hough_circle.cpp -I/usr/local/lib -lopencv_bioinspired -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_cudaarithm -lopencv_cudabgsegm -lopencv_cudacodec -lopencv_cudafeatures2d -lopencv_cudafilters -lopencv_cudaimgproc -lopencv_cudaoptflow -lopencv_cuda -lopencv_cudastereo -lopencv_cudawarping -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_optim -lopencv_photo -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab

opencv:
	g++ opencv.cpp -I/usr/local/lib -lopencv_bioinspired -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_cudaarithm -lopencv_cudabgsegm -lopencv_cudacodec -lopencv_cudafeatures2d -lopencv_cudafilters -lopencv_cudaimgproc -lopencv_cudaoptflow -lopencv_cuda -lopencv_cudastereo -lopencv_cudawarping -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_optim -lopencv_photo -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab

